{
    'name': 'Finance Stock Analyse',
    'summary': 'Finance Stock Analyse',
    'category': 'Tools',
    'author': '1di0t',
    'license': 'LGPL-3',
    'installable': True,
    'depends': ['base', 'queue_job'],
    'external_dependencies': {
        'python': ['tushare'],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/mine_type.xml',
        'data/stock_compare.xml',
        'views/finance_stock.xml',
        'views/stock_main_data.xml',
        'views/stock_zcfzb.xml',
        'views/stock_report.xml',
        'views/stock_business.xml',
        'views/stock_analyse.xml',
        'views/finance_stock_holder.xml',
        'views/finance_stock_share_holder.xml',
        'views/stock_lrb.xml',
        'views/finance_settings.xml',
        'views/stock_compare_analysis.xml',
        'views/mine_type.xml',
        'views/finance_company_event.xml',
        'views/finance_checklist.xml',
        'views/finance_event_type.xml',
        'views/stock_fiscal_data.xml',
        'views/finance_stock_xjllb.xml',
        'views/compare_benchmark_data.xml',
        'views/finance_stock_bonus.xml',
        'views/finance_stock_share_holder_news.xml',
        'views/webclient_templates.xml',
        'views/operate_customer_supplier.xml',
        'views/finance_stock_company_manger.xml',
    ],
}
